class SVGMap {
  static Map<String, String> map = {
    'cottage': './assets/svgs/icons/cottage.svg',
    'building-user-solid': './assets/svgs/icons/building-user-solid.svg',
    'bed': './assets/svgs/icons/bed.svg',
    'wind': './assets/svgs/icons/wind.svg',
    'microwave': './assets/svgs/icons/microwave.svg',
    'moving': './assets/svgs/icons/moving.svg',
    'gmail': './assets/svgs/icons/gmail.svg',
    'fan-solid': './assets/svgs/icons/fan-solid.svg',
    'home': './assets/svgs/icons/home.svg',
    'loupe': './assets/svgs/icons/loupe.svg',
    'service': './assets/svgs/icons/service.svg',
    'recent': './assets/svgs/icons/recent.svg',
    'historique': './assets/svgs/icons/historique.svg',
    'villa': './assets/svgs/icons/villa.svg',
    'directions_car': './assets/svgs/icons/directions_car.svg',
    'kitchen-set-solid': './assets/svgs/icons/kitchen-set-solid.svg',
    'tv': './assets/svgs/icons/tv.svg',
    'volume_off': './assets/svgs/icons/volume_off.svg',
    'terrain': './assets/svgs/icons/terrain.svg',
    'smile-circle-svgrepo-com': './assets/svgs/icons/smile-circle-svgrepo-com.svg',
    'visua': './assets/svgs/icons/visua.svg',
    'wifi': './assets/svgs/icons/wifi.svg',
    'resi': './assets/svgs/icons/resi.svg',
    'panier': './assets/svgs/icons/panier.svg',
    'oven': './assets/svgs/icons/oven.svg',
    'compte': './assets/svgs/icons/compte.svg',
    'facebook': './assets/svgs/icons/facebook.svg',
    'google': './assets/svgs/icons/google.svg',
    'coeur': './assets/svgs/icons/coeur.svg',
    'meubles': './assets/svgs/icons/meubles.svg',
    'home_FILL': './assets/svgs/icons/home_FILL.svg',
    'kitchen': './assets/svgs/icons/kitchen.svg',
    'google_maps': './assets/svgs/icons/google_maps.svg',
    'coeur2': './assets/svgs/icons/coeur2.svg',
    'location': './assets/svgs/icons/location.svg',
    'coeur1': './assets/svgs/icons/coeur1.svg',
    'local_laundry': './assets/svgs/icons/local_laundry.svg',
    'dry_cleaning': './assets/svgs/icons/dry_cleaning.svg',
  };
}
