class FurnitureTaxonomy {
  static const Map<String, String> categoryLabels = {
    'salon': 'Salon',
    'chambre': 'Chambre',
    'literie': 'Literie',
    'cuisine-salle-a-manger': 'Cuisine & salle à manger',
    'salle-de-bain': 'Salle de bain',
    'bureau': 'Bureau',
    'rangement': 'Rangement',
    'decoration': 'Décoration',
    'eclairage': 'Éclairage',
    'mobilier-exterieur': 'Mobilier extérieur',
    'enfant-bebe': 'Enfant & bébé',
    'electromenager': 'Électroménager',
    'multimedia': 'Multimédia',
    'evenementiel': 'Événementiel',
    'commerce-professionnel': 'Commerce & professionnel',
    'autre': 'Autre',
  };

  static const Map<String, List<String>> typesByCategory = {
    'salon': [
      'canape',
      'canape-angle',
      'fauteuil',
      'pouf',
      'table-basse',
      'meuble-tv',
      'console',
      'bibliotheque',
      'vitrine',
      'banquette',
      'table-appoint',
      'meuble-bar',
      'rocking-chair',
      'repose-pieds',
    ],
    'literie': [
      'sommier',
      'matelas-orthopedique',
      'matelas-memoire-forme',
      'surmatelas',
      'protege-matelas',
      'oreiller',
      'traversin',
      'parure-de-lit',
      'couette',
      'couverture',
    ],
    'chambre': [
      'lit-simple',
      'lit-double',
      'lit-superpose',
      'matelas',
      'tete-de-lit',
      'table-de-nuit',
      'armoire',
      'commode',
      'dressing',
      'coiffeuse',
      'lit-coffre',
      'valet-de-nuit',
      'porte-vetements',
    ],
    'cuisine-salle-a-manger': [
      'table-a-manger',
      'chaise',
      'tabouret',
      'buffet',
      'vaisselier',
      'ilot-central',
      'desserte',
      'meuble-bas-cuisine',
      'meuble-haut-cuisine',
      'plan-de-travail',
      'bar-cuisine',
      'chariot-cuisine',
      'range-bouteilles',
      'banc-cuisine',
      'meuble-evier',
    ],
    'salle-de-bain': [
      'meuble-vasque',
      'armoire-toilette',
      'colonne-salle-de-bain',
      'etagere-salle-de-bain',
      'miroir-salle-de-bain',
      'banc-salle-de-bain',
      'panier-linge',
      'porte-serviettes',
      'tabouret-salle-de-bain',
      'meuble-lavabo',
    ],
    'bureau': [
      'bureau-droit',
      'bureau-angle',
      'chaise-bureau',
      'fauteuil-bureau',
      'caisson',
      'etagere-bureau',
      'bibliotheque-bureau',
      'table-reunion',
      'cloison-separation',
      'meuble-imprimante',
      'support-ecran',
      'bureau-assis-debout',
      'repose-pieds-bureau',
      'tableau-blanc',
      'vestiaire-bureau',
    ],
    'rangement': [
      'etagere',
      'armoire-rangement',
      'commode-rangement',
      'colonne-rangement',
      'placard',
      'meuble-chaussures',
      'coffre-rangement',
      'casiers',
      'rayonnage',
      'classeur',
      'porte-manteau',
      'penderie',
      'boite-rangement',
      'organisateur',
      'meuble-entree',
    ],
    'decoration': [
      'miroir',
      'tapis',
      'tableau',
      'cadre',
      'statue',
      'vase',
      'paravent',
      'horloge',
      'rideaux',
      'accessoire-deco',
      'papier-peint',
      'plante-artificielle',
      'bougie-deco',
      'objet-artisanal',
      'nappe-chemin-table',
    ],
    'eclairage': [
      'lampe-table',
      'lampe-bureau',
      'lampadaire',
      'suspension',
      'plafonnier',
      'applique-murale',
      'spot',
      'veilleuse',
      'guirlande-lumineuse',
      'abat-jour',
      'projecteur',
      'lampe-led',
      'lampe-solaire',
      'reglette-lumineuse',
      'liseuse',
    ],
    'mobilier-exterieur': [
      'table-jardin',
      'chaise-jardin',
      'fauteuil-exterieur',
      'canape-exterieur',
      'salon-jardin',
      'banc-jardin',
      'transat',
      'bain-de-soleil',
      'hamac',
      'parasol',
      'balancelle',
      'coffre-exterieur',
      'barbecue-mobile',
      'pergola',
      'chaise-pliante-exterieur',
    ],
    'enfant-bebe': [
      'lit-bebe',
      'lit-enfant',
      'table-a-langer',
      'armoire-enfant',
      'commode-enfant',
      'bureau-enfant',
      'chaise-enfant',
      'coffre-a-jouets',
      'etagere-enfant',
      'parc-bebe',
      'berceau',
      'chaise-haute',
      'bureau-ado',
      'lit-evolutif',
      'table-activites',
    ],
    'electromenager': [
      'refrigerateur',
      'congelateur',
      'cuisiniere',
      'four',
      'micro-ondes',
      'lave-linge',
      'seche-linge',
      'lave-vaisselle',
      'climatiseur',
      'ventilateur',
    ],
    'multimedia': [
      'televiseur',
      'support-tv',
      'home-cinema',
      'barre-de-son',
      'enceinte',
      'videoprojecteur',
      'ecran-ordinateur',
      'console-jeu',
      'routeur-wifi',
      'onduleur',
    ],
    'evenementiel': [
      'table-pliante',
      'chaise-pliante',
      'housse-chaise',
      'nappage',
      'podium',
      'stand-exposition',
      'chapiteau',
      'mange-debout',
      'bar-mobile',
      'chauffage-exterieur',
    ],
    'commerce-professionnel': [
      'comptoir',
      'presentoir',
      'vitrine-magasin',
      'rayonnage-magasin',
      'chaise-attente',
      'banque-accueil',
      'table-restaurant',
      'chaise-restaurant',
      'mobilier-hotel',
      'meuble-caisse',
      'etagere-stockage-pro',
      'armoire-metallique',
      'chariot-service',
      'casier-consigne',
      'table-inox',
    ],
    'autre': [
      'autre',
    ],
  };
}
